apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://{{.Values.samlEndpoint}}.{{.Values.ingressDomain}}/user"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{.Values.samlEndpoint}}.{{.Values.ingressDomain}}/saml/login/example-okta-com"
    nginx.ingress.kubernetes.io/auth-snippet: |
      resolver 127.0.0.53 valid=15s;
spec:
  ingressClassName: nginx
  rules:
    - host: firewalled.{{.Values.ingressDomain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 443
