apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    app: {{ .Release.Name }}
spec:
  containers:
    - name: nginx
      image: {{ .Values.containerFront }}
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80